name: ferry_app
description: My graduation desifn ferry&#x27;s Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  dio:
  rxdart:
  common_utils:
  cupertino_icons:
  mqtt_client:
  web_socket_channel:
  charts_flutter:
  fluttertoast:
  #高德地图
  amap_base:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/login.jpg
    - assets/ship.obj
    
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf