server:
  port: 8080
  servlet:
    context-path: /ferry
spring:
  datasource:
    url: jdbc:mysql://132.232.22.168:3306/ferry?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: luooyii
    password: Abc996688+
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: null
#    timeout: 5000ms
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        max-wait: 100000ms
  resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${interest.properties.paths-properties.image}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.luooyii.ferry.server.model

logging:
  file: D:/Project/Beacono/ferry/file/logs/interest.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest: DEBUG

##自定义配置
interest:
  properties:
    paths-properties:
      image: D:/Project/Beacono/ferry/file/image
#      domain-name: http://www.lovemtt.com/interest
      domain-name: http://127.0.0.1:8080/ferry

